services:
  debate_dragon:
    volumes:
      - type: bind
        source: ./db
        target: /bot/db
    build: ./
    restart: "always"
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: docker.io/library/postgres:18
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
