# fly.toml app configuration file generated for debate-dragon-2 on 2023-10-23T19:53:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "debate-dragon-2"
primary_region = "yyz"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
kill_timeout = "200"
