// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanup_messages_table.sql

package db

import (
	"context"
)

const cleanupMessagesTable = `-- name: CleanupMessagesTable :exec
DELETE FROM messages WHERE id NOT IN (SELECT id FROM messages ORDER BY created_at DESC LIMIT 10000)
`

func (q *Queries) CleanupMessagesTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupMessagesTable)
	return err
}
