// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_deleted_message_by_author_id.sql

package db

import (
	"context"
)

const getDeletedMessagesByAuthorID = `-- name: GetDeletedMessagesByAuthorID :one
SELECT id, guild_id, author_id, metadata, created_at, deleted, message_id, channel_id
FROM messages
WHERE author_id = $1 AND guild_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetDeletedMessagesByAuthorIDParams struct {
	AuthorID string
	GuildID  string
}

// GetDeletedMessagesByAuthorID gets a specific author's latest deleted message in a specific guild
func (q *Queries) GetDeletedMessagesByAuthorID(ctx context.Context, arg GetDeletedMessagesByAuthorIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, getDeletedMessagesByAuthorID, arg.AuthorID, arg.GuildID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.AuthorID,
		&i.Metadata,
		&i.CreatedAt,
		&i.Deleted,
		&i.MessageID,
		&i.ChannelID,
	)
	return i, err
}
