// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_deleted_message_by_guild_id.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeletedMessagesByGuildID = `-- name: GetDeletedMessagesByGuildID :one
SELECT id, guild_id, author_id, metadata, created_at
FROM messages
WHERE guild_id = $1
ORDER BY created_at DESC
LIMIT 1
`

type GetDeletedMessagesByGuildIDRow struct {
	ID        pgtype.UUID
	GuildID   string
	AuthorID  string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

// GetDeletedMessagesByGuildID gets a specific guild's latest deleted message in a specific guild
func (q *Queries) GetDeletedMessagesByGuildID(ctx context.Context, guildID string) (GetDeletedMessagesByGuildIDRow, error) {
	row := q.db.QueryRow(ctx, getDeletedMessagesByGuildID, guildID)
	var i GetDeletedMessagesByGuildIDRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.AuthorID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
