// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_deleted_message_by_author_id.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeletedMessagesByAuthorID = `-- name: GetDeletedMessagesByAuthorID :one
SELECT id, guild_id, author_id, metadata, created_at
FROM messages
WHERE author_id = $1 AND guild_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetDeletedMessagesByAuthorIDParams struct {
	AuthorID string
	GuildID  string
}

type GetDeletedMessagesByAuthorIDRow struct {
	ID        pgtype.UUID
	GuildID   string
	AuthorID  string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

// GetDeletedMessagesByAuthorID gets a specific author's latest deleted message in a specific guild
func (q *Queries) GetDeletedMessagesByAuthorID(ctx context.Context, arg GetDeletedMessagesByAuthorIDParams) (GetDeletedMessagesByAuthorIDRow, error) {
	row := q.db.QueryRow(ctx, getDeletedMessagesByAuthorID, arg.AuthorID, arg.GuildID)
	var i GetDeletedMessagesByAuthorIDRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.AuthorID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
