// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_channel_message.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChannelMessages = `-- name: GetChannelMessages :many
SELECT id, guild_id, author_id, metadata, created_at, deleted, message_id, channel_id
FROM messages
WHERE channel_id = $1 AND guild_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type GetChannelMessagesParams struct {
	ChannelID pgtype.Text
	GuildID   string
	Limit     int32
}

// GetChannelMessages gets the past number of messages from a specific channel in a specific guild
func (q *Queries) GetChannelMessages(ctx context.Context, arg GetChannelMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getChannelMessages, arg.ChannelID, arg.GuildID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.AuthorID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Deleted,
			&i.MessageID,
			&i.ChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
