// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_deleted_message_by_guild_id.sql

package db

import (
	"context"
)

const getDeletedMessagesByGuildID = `-- name: GetDeletedMessagesByGuildID :many
SELECT id, guild_id, author_id, metadata, created_at, deleted, message_id
FROM messages
WHERE guild_id = $1 AND deleted = true
ORDER BY created_at DESC
LIMIT 1
`

// GetDeletedMessagesByGuildID gets a specific guild's latest deleted message in a specific guild
//
// There may not be any deleted messages in a guild, so this query may return 0 rows
func (q *Queries) GetDeletedMessagesByGuildID(ctx context.Context, guildID string) ([]Message, error) {
	rows, err := q.db.Query(ctx, getDeletedMessagesByGuildID, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.AuthorID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Deleted,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
