// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_message.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (id, guild_id, author_id, metadata)
VALUES ($1, $2, $3, $4)
`

type InsertMessageParams struct {
	ID       pgtype.UUID
	GuildID  string
	AuthorID string
	Metadata []byte
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.ID,
		arg.GuildID,
		arg.AuthorID,
		arg.Metadata,
	)
	return err
}
