// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mark_message_deleted.sql

package db

import (
	"context"
)

const markMessageDeleted = `-- name: MarkMessageDeleted :exec
UPDATE messages
SET deleted = TRUE
WHERE message_id = $1 AND guild_id = $2
`

type MarkMessageDeletedParams struct {
	MessageID string
	GuildID   string
}

// MarkMessageDeleted marks a message in a guild as deleted
func (q *Queries) MarkMessageDeleted(ctx context.Context, arg MarkMessageDeletedParams) error {
	_, err := q.db.Exec(ctx, markMessageDeleted, arg.MessageID, arg.GuildID)
	return err
}
