// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Table containing all messages send in all guilds this bot is in
type Message struct {
	ID pgtype.UUID
	// Guild ID this message came from
	GuildID string
	// Author ID this message came from
	AuthorID string
	// JSON encoded string, containg other properties, such as image and attachments
	Metadata []byte
	// Timestamp the message was created at
	CreatedAt pgtype.Timestamptz
	Deleted   bool
	MessageID string
	ChannelID pgtype.Text
}
