// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        pgtype.UUID
	GuildID   string
	AuthorID  string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}
