name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v ./...

  # GenerateRelease:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - Build
  #   env:
  #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - name: Generate release
  #       run: npx semantic-release

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # needs:
    #   - Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create .env
        run: echo "TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env

      - name: Deploy application
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
